services:
  - type: web
    name: kikabon
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./public
    routes:
      - type: rewrite
        source: /play
        destination: /player.html
      - type: rewrite
        source: /admin
        destination: /index.html
